homebrew: remove no longer needed workflow
The `git-credential-manager` cask is part of the 'autobump' for the
public tap of Homebrew.

We no longer need to maintain our own publishing workflow.

Error message when we try to publish our own package bump:

```log
Error: Whoops, the git-credential-manager cask has its version update
pull requests automatically opened by BrewTestBot every ~3 hours!
We'd still love your contributions, though, so try another one
that's not in the autobump list:
  https://github.com/Homebrew/homebrew-cask/blob/master/.github/autobump.txt
```